config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'thanks' => 'pages#thanks'
  resources :signups

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def contact
  end
  def thanks
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @signup = Signup.new
  end
  def create
    @signup = Signup.new(signup_params)
    if @signup.save
      redirect_to thanks_path
    else
      render 'new'
    end
  end
  
  private
  def signup_params
    params.require(:signup).permit(:firstname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,100,300" rel="stylesheet" type="text/css">
  <!-- Your other stuff  (you can have problems if you don't add minimum scale in the viewport) -->
    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <!-- Include a Sidr bundled CSS theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.sidr/2.2.1/stylesheets/jquery.sidr.dark.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>  
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='sidr' class="menu" style="left: -240px;">
    <ul>
      <li><%= link_to "Home", root_path %></li> <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", new_signup_path %></li>
    </ul> 
    <img alt="Close" class="icon-close" src="https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/close-white.svg" width="24px">
  </div>

<%= yield %>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//cdn.jsdelivr.net/jquery/2.2.0/jquery.min.js"></script>
  <script src="//cdn.jsdelivr.net/jquery.sidr/2.2.1/jquery.sidr.min.js"></script>
  <script>
  $(document).ready(function() {
      $('.icon-menu').sidr({});
    	$('.icon-close').sidr('close','sidr');
  });
  </script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-main">
  <img alt="Open" class="icon-menu" src="https://stories-rails.herokuapp.com/assets/open-9688b19dacd0cc7d027490776ace74ff.svg" width="24px">
  <div class="content container">
    <h1>Relive your favorite memories</h1>
  </div>
</div>
<div class="about-supporting">
  <div class="container">
    <h2>No more sorting through photos</h2>
    <p>Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</p>
    <p><%= link_to 'Sign up', new_signup_path, class: 'btn btn-primary' %></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-main"> 
  <img alt="Open" class="icon-menu" src="https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/menu-white.svg" width="24px"> 
  <div class="container"> 
    <div class="row"> 
      <div class="content col-md-6 col-md-offset-6"> 
        <h1>Create and share Stories</h1> 
        <p>
          <%= link_to 'Learn more', about_path, class: 'btn btn-primary' %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="home-supporting">
  <div class="container">
    <h2>Relive and share your adventures</h2>
    <p>Stories automatically creates a digital journal filled with only your best photos.</p>
  </div>
</div>
<div class="home-secondary">
  <div class="container">
  </div>
</div>
<div class="home-about">
  <div class="container">
    <h2>Discover Stories</h2>
    <p><%= link_to 'Learn more', about_path, class: 'btn btn-primary' %></p>
  </div>
</div>

app/views/pages/thanks.html.erb
<div class="contact-main">
  <img alt="Open" class="icon-menu" src="https://stories-rails.herokuapp.com//assets/open-9688b19dacd0cc7d027490776ace74ff.svg" width="24px">
  <div class="content container">
    <h1>Thanks. We'll be in touch.</h1>
  </div>
</div>

app/views/signups/new.html.erb
<div class="contact-main"> <img alt="Open" class="icon-menu" src="https://stories-rails.herokuapp.com/assets/open-9688b19dacd0cc7d027490776ace74ff.svg" width="24px">
  <div class="content container">
    <h1>Get the latest updates from Stories</h1>
    <div class="row">
      <div class="col-md-4 col-md-4-offset"></div>
      <div class="col-md-4">
        <form accept-charset="UTF-8" action="/signups" class="new_signup" id="new_signup" method="post">
          <div style="display:none">
            <input name="utf8" type="hidden" value="✓">
            <input name="authenticity_token" type="hidden" value="OizjpBshDmRY3QT0wsoPQwbi8Xu3wD9nJIOXHAogtzA="></div>
          <div class="form-group">
            <label>First name</label>
            <input class="form-control" id="signup_firstname" name="signup[firstname]" type="text"> </div> <div class="form-group">
          <label>Email</label>
          <input class="form-control" id="signup_email" name="signup[email]" type="text">
          </div>
          <input class="btn btn-default" name="commit" type="submit" value="Join">
        </form>
      </div>
    </div>
    <div class="col-md-4 col-md-4-offset"></div>
  </div>
</div>